### ISSUE TITLE
Callback necessary?

### ISSUE THREAD

**Issue by ericdfields** [nathan7/xhr-json#2]
Callback shouldn't be necessary for this, right? I swear I had this working right in my app yesterday with simply `xhrJson( myUrl )`, but now I'm getting `callback argument missing` errors. Any insight? Happy to provide more details. Thanks.

**Comment by edef1c** [comment]
It shouldn't, no. Sure you're requiring the right module? The string `callback argument missing` doesn't appear in this module or its dependencies.

**Comment by ericdfields** [comment]
I'm really not sure what happened here, but It's back to working as expected. Something to do with my webpack config, no doubt. Thank you for responding.
